project:
  type: website
  output-dir: docs

website:
  title: "Mario Nonog"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: resume.qmd
        text: Resume
      - href: project.qmd
        text: Projects
      - href: certificates.qmd
        text: Certificates
      - href: presentations.qmd
        text: Presentations
      - href: Research.qmd
        text: Research
    right:
      - icon: github
        href: https://github.com/rsm-mnonog
        text: "GitHub"
        target: _blank
  page-footer:
    center: "© 2026 Mario Nonog · built with Quarto"
    border: false

format:
  html:
    theme: zephyr
    css: styles.css
    doc: true
    linkcolor: "#1F3A93"




